defaults: &defaults
  app_versions:
    recommended_frequency: 5
    device_usage_enabled: true
    ios:
      app_url: "https://google.com"
      package_name: "com.google"
    android:
      app_url: "https://google.com"
      package_name: "com.google"
  sidekiq:
    redis_uri: "redis://redis:6379/0"
  newrelic:
    license_key: "none"
    app_name: Dome Lite
    monitor_mode: false
    log_level: "info"
  order_refresh_secs: 20
  orders:
    expiry:
      expiry_minutes: 15
      prayer_time_exception: true
  pub_sub:
    sleep_in_sync_listen: 1
    default:
      type: "123"
      project_id: "project"
      private_key_id: "123"
      private_key: "123"
      client_email: "123"
      client_id: "123"
      auth_uri: "123"
      token_uri: "123"
      auth_provider_x509_cert_url: "123"
      client_x509_cert_url: "123"
    store:
      enabled: true
      topics:
        update_store_status: "DomeStoreUpdated"
        update_store_pos_activation: "DomeStoreUpdated"
        update_store_working_hours: "DomeStoreUpdated"
        update_store_menu: "DomeStoreUpdated"
        created_store: "POSStoreCreated"
        updated_store: "DomeStoreUpdated"
      event_names:
        ready: "POSStoreReady"
        busy: "POSStoreBusy"
        pos_activated: "POSStoreActivated"
        pos_deactivated: "POSStoreDeActivated"
        menu_updated: "POSStoreMenuUpdated"
        working_hours_updated: "POSStoreWorkingHoursUpdated"
        created_store: "POSStoreCreated"
        updated_store: "DomeStoreUpdated"
    catalog:
      enabled: true
      topics:
        catalog_updated: "DomeCatalogUpdated"
      event_names:
        content_updated: "POSCatalogContentUpdated"
        assigned: "POSCatalogAssigned"
    order:
      type: "123"
      project_id: "project"
      private_key_id: "123"
      private_key: "123"
      client_email: "123"
      client_id: "123"
      auth_uri: "123"
      token_uri: "123"
      auth_provider_x509_cert_url: "123"
      client_x509_cert_url: "123"
      enabled: true
      log_data: true
      sync_listen: true
      topics:
        create: "SwyftOrderCreated"
        update: "SwyftOrderUpdated"
        update_status: "DomeOrderUpdated"
      event_names:
        accepted: "POSOrderAccepted"
        received: "POSOrderRecieved"
        rejected: "POSOrderRejected"
        delivered: "POSOrderDelivered"
      subscriptions:
        create: "swyft-order-created"
        update: "swyft-order-updated"
    brand:
      enabled: true
      topics:
        brand_created: "POSBrandCreated"
        brand_updated: "POSBrandUpdated"
      event_names:
        brand_created: "POSBrandCreated"
        brand_updated: "POSBrandUpdated"
    store_items:
      enabled: true
      topics:
        out_of_stock_items: "POSCatalogItemUpdated"
      event_names:
        out_of_stock_items: "StoreOutOfStockCatalogItemUpdated"
  fcm_messages:
    private_key: "private key"
    client_email: "client email"
    project_name: "project name"
  deeplinks:
    dome_lite: "dome lite"
  firebase:
    app_config:
      apiKey: "A"
      authDomain: "B"
      projectId: "C"
    credential:
      type: "service_account"
      project_id: "A"
      private_key_id: "B"
      private_key: "C"
      client_email: "D"
      client_id: "E"
      auth_uri: "F"
      token_uri: "G"
      auth_provider_x509_cert_url: "H"
      client_x509_cert_url: "I"
  google_bucket:
    project_name: "swyft-staging"
    google_storage_access_key_id: "1234"
    google_storage_secret_access_key: "5678"
    bucket_name: "swyft-staging"
    host: "https://swyft-staging.storage.googleapis.com"

  services:
    sentry:
      dsn: ""
      environment: "production"
    launchdarkly:
      api_key: ""
      config:
        connect_timeout: 0.5
        read_timeout: 0.5
  menu_jwt:
    hmac_secret: "secure secret"
    expiry:
      hours: 4
      minutes: 0
  cities:
    end_point: 'url for cities'

  store_status:
    redis_uri: "redis://redis:6379/1"
  integrations:
    number_of_threads_for_syncing: 10

  zendesk:
    subdomain: "localhost"
    url: "localhost"
    email: "localhost"
    shared_secret_token: "localhost"
    app_client_id: "localhost"
    app_id: "localhost"
    chat_token: "localhost"
    our_own_signing_token: "localhost"
    default_requester: "localhost"
    api_shared_secret_token: "localhost"
    order_id_ticket_field_id: "localhost"
    account_support_tag: "localhost"
  accounts:
    email_format: "%{username}@lite.usepace.ninja"
  tickets:
    time_cap:
      minutes_to_create_next_ticket: 1
      maximum_tickets: 100
      type_filtering: true
      general:
        minutes_to_create_next_ticket: 1
        maximum_tickets: 100
        type_filtering: false
      order:
        minutes_to_create_next_ticket: 1
        maximum_tickets: 100
        type_filtering: true
  pace_api:
    url: 'https://logistics-backend.usepace.ninja'
    client_id: 'CWg7_Q1hSN_cFiN30aD_XQ'
    client_secret: '4DY-chCVlygcsIb0pWp4sw'
  assets_api:
    url: https://europe-west1-tmt-assets.cloudfunctions.net
    token: "10000000-2000-3000-4000-500000000000"

development:
  <<: *defaults
  secret_key_base: a80862fee446e68cf983a2a42b09031d7628518f0f96d6773ec4fbc2b054020572cb5cfc0536ff516ca5e9084f9c9ce9f0742fdd9282ab2e962c9721849fb2bb
  database:
    pool: 5
    database: "app_development"
    host: postgres
    port: 5432
    username: "postgres"
    password: "mysecret"
  integrations:
    number_of_threads_for_syncing: 1

test:
  <<: *defaults
  secret_key_base: 4c76cc6b0752d298d3bba7b60de17de37825d61dde6a8ea559294847043683358fef5e8c40903ca025d4a297ccba9034d993e4453e256ad54c8d0db8f5a44577
  database:
    pool: 5
    database: "app_test"
    host: postgres
    port: "5432"
    username: "postgres"
    password: "mysecret"

  integrations:
    number_of_threads_for_syncing: 1
