apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-configs
  namespace: {{ .Release.Namespace }}
data: 
  secrets.yml: |
    production:
      secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
      order_refresh_secs:
      database:
        pool: 40
        database: platform
        host: {{ .Release.Name }}-postgresql
        port: 5432
        username: <%= ENV["DATABASE_USERNAME"] %>
        password: <%= ENV["DATABASE_PASSWORD"] %>
      app_versions:
        recommended_frequency: 5
        device_usage_enabled: true
        ios:
          app_url: 'https://apps.apple.com/tr/app/dome-lite/id1468877909'
          package_name: 'com.usepace.domelite.staging'
        android:
          app_url: 'https://google.com'
          package_name: 'com.google'
      sidekiq:
        redis_uri: "redis://{{ .Release.Name }}-redis-master:6379/15"
        username: <%= ENV["SIDEKIQ_USERNAME"] %>
        password: <%= ENV["SIDEKIQ_PASSWORD"] %>
      store_status:		
        redis_uri: "redis://{{ .Release.Name }}-redis-master:6379/14"
      orders:
        expiry:
          expiry_minutes: 1
          prayer_time_exception: false
      newrelic:
        license_key: "none"
        app_name: "Dome Lite (Staging)"
        monitor_mode: false
        log_level: "info"
      pub_sub:
        sleep_in_sync_listen: 1
        store:
          enabled: true
          topics:
            update_store_status:         "DomeStoreUpdated"
            update_store_pos_activation: "DomeStoreUpdated"
            update_store_working_hours:  "DomeStoreUpdated"
            update_store_menu:           "DomeStoreUpdated"
            created_store:               "POSBrandStoreUpdated"
            updated_store:               "POSBrandStoreUpdated"
          event_names:
            ready:                 "POSStoreReady"
            busy:                  "POSStoreBusy"
            pos_activated:         "POSStoreActivated"
            pos_deactivated:       "POSStoreDeActivated"
            menu_updated:          "POSStoreMenuUpdated"
            working_hours_updated: "POSStoreWorkingHoursUpdated"
            created_store:         "POSStoreCreated"
            updated_store:         "DomeStoreUpdated"
        order:
          enabled: true
          log_data: true
          sync_listen: true
          topics:
            create: "SwyftOrderCreated"
            update: "SwyftOrderUpdated"
            update_status: "DomeOrderUpdated"
          event_names:
            accepted: "POSOrderAccepted"
            received: "POSOrderReceived"
            rejected: "POSOrderRejected"
          subscriptions:
            create: "swyft-order-created"
            update: "swyft-order-updated"
        catalog:
          enabled: true
          topics:
            catalog_updated: "DomeCatalogUpdated"
          event_names:
            content_updated: "POSCatalogContentUpdated"
            assigned: "POSCatalogAssigned"
        brand:
          enabled: true
          topics:
            brand_created: "POSBrandStoreUpdated"
            brand_updated: "POSBrandStoreUpdated"
          event_names:
            brand_created: "POSBrandCreated"
            brand_updated: "POSBrandUpdated"
        store_items:
          enabled: true
          topics:
            out_of_stock_items: "POSCatalogItemUpdated"
          event_names:
            out_of_stock_items: "StoreOutOfStockCatalogItemUpdated"
      fcm_messages:
        project_name: <%= ENV["GOOGLE_CLOUD_PROJECT"] %>
      deeplinks:
        dome_lite: "domeliteapp"
      google_bucket:
        project_name:
        google_storage_access_key_id:
        google_storage_secret_access_key:
        bucket_name:
        host:
      firebase:
        app_config:
          apiKey: <%= ENV["FIREBASE_APP_CONFIG_APIKEY"] %>
          authDomain: "dome-platform-staging.firebaseapp.com"
          projectId: <%= ENV["GOOGLE_CLOUD_PROJECT"] %>
          private_key: <%= ENV["PLATFORM_SERVICE_ACCOUNT_PRIVATE_KEY"] %>
          client_email: "platform@dome-platform-staging.iam.gserviceaccount.com"
      integrations:
        number_of_threads_for_syncing: 10
      services:
        sentry:
          dsn: <%= ENV["SENTRY_DSN"] %>
          app_env: <%= ENV["APP_ENV"] %>
      menu_jwt:
        hmac_secret: <%= ENV["MENU_JWT_HMAC_SECRET"] %>
        expiry:
          hours: 4
          minutes: 0
      tickets:
        time_cap:
          minutes_to_create_next_ticket: 1
          maximum_tickets: 100
          type_filtering: true
          general:
            minutes_to_create_next_ticket: 1
            maximum_tickets: 100
            type_filtering: false
          order:
            minutes_to_create_next_ticket: 1
            maximum_tickets: 100
            type_filtering: true
      zendesk:
        subdomain: stg1.zendesk.com
        url: https://stg1.zendesk.com
        email: mazen@maz3n.com
        shared_secret_token: <%= ENV["ZENDESK_SHARED_SECRET_TOKEN"] %> 
        app_client_id: mobile_sdk_client_ac56c0ae018302118749
        app_id: e15f11a9a9b2138afcb16158559d6909bc9a7ecbc61d90ab
        chat_token: <%= ENV["ZENDESK_CHAT_TOKEN"] %>
        our_own_signing_token: <%= ENV["ZENDESK_OUR_OWN_SIGNING_TOKEN"] %>
        default_requester: 362018817159
        api_shared_secret_token: <%= ENV["ZENDESK_API_SHARED_SECRET_TOKEN"] %>
        order_id_ticket_field_id: 360003280080
        account_support_tag: dome_account_support
      accounts:
        email_format: "%{username}@lite.usepace.ninja"
      assets_api:
        url: https://europe-west1-tmt-assets.cloudfunctions.net
        token: <%= ENV["ASSETS_API_TOKEN"] %>
      cities:
        end_point: https://gist.githubusercontent.com/ahmadhussain/8e23c2d0fd3a3b82a98f72f428bc9837/raw/26dc3643a9ed34cb20df11fc5d31c910e7938d72/zones.geojson
