name: TMT-Charts-CI

on: pull_request
  
jobs:
  build:
    steps:
    - name: Merge branch delete name
      uses: jessfraz/branch-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NO_BRANCH_DELETED_EXIT_CODE: "0"

  