name: chart publish

on:
  push:
    branches:
      - master
      - junk-ci

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://rizwan937/helm

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Validate and Upload Chart to Chart Museum
      env:
        TMT_CHARTS_USERNAME: ${{ secrets.TMT_CHARTS_USERNAME}}
        TMT_CHARTS_PASSWORD: ${{ secrets.TMT_CHARTS_PASSWORD }}
      run: |
        export PAGER=$(git diff-tree --no-commit-id --name-only -r HEAD)
        echo "Changed Components are  => $PAGER"
        export COMPONENT="NOTSET"
        unique_dirs=($(tr ' ' '\n' <<< "${PAGER[@]}" | sort -u | tr '\n' ' '))

        echo "CHANGED DIRS ARE::::"
        for dir in ${unique_dirs[@]}
        do
          echo $dir        
          if [[ "$dir" == .* ]]; then del="$dir"; fi
        done
        echo "Getting Unique Values:::"

        unique_dirs=("${unique_dirs[@]/$del}")
        echo "Unique Values Are:::"
        echo ${unique_dirs[@]}


        for dir in ${unique_dirs[@]}
        do
          echo $dir | cut -f1 -d"/"
          export COMPONENT_DIR="${dir%%/*}"
          echo "Changed Dir => $COMPONENT_DIR"
          cd $COMPONENT_DIR
          echo "Initialize Helm and Upload Chart If Exists"
          helm init --client-only
          echo "Helm Adding Chart repo"
          helm repo add charts https://charts.tmt.tools --username $TMT_CHARTS_USERNAME --password $TMT_CHARTS_PASSWORD
          helm dep build
          helm package .
          FILENAME="$(find . \( -name "$COMPONENT_DIR*.tgz" \) -exec basename {} \;)"
          if [ "$FILENAME" == "" ]; then echo "No Chart Version Found!" && exit 1;  fi
          echo $FILENAME
          curl --user $TMT_CHARTS_USERNAME:$TMT_CHARTS_PASSWORD --data-binary "@$FILENAME" https://charts.tmt.tools/api/charts
        done