name: TMT-Charts-CI

on: 
  pull_request
    types: [closed]

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Merge branch delete
      uses: jessfraz/branch-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NO_BRANCH_DELETED_EXIT_CODE: 0

  