name: Publish

on:
  push:
    branches:
      - master
      - staging
      - junk-ci

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Build Image and Publish
      env:
          BRANCH: ${{ github.event.ref }}
          STAGING_GCLOUD_SERVICE_ACCOUNT: ${{ secrets.STAGING_GCLOUD_SERVICE_ACCOUNT }}
          PRODUCTION_GCLOUD_SERVICE_ACCOUNT: ${{ secrets.PRODUCTION_GCLOUD_SERVICE_ACCOUNT }}
          
      run: |
        BRANCH=${BRANCH#refs/heads/}
        echo $BRANCH
        
        if [ $BRANCH == "master" ]; then
          APP_ENV=production
        elif [ $BRANCH == "staging" ]; then
          APP_ENV=staging
        elif [ $BRANCH == "junk-ci" ]; then
          APP_ENV=staging
        fi
        
        GCLOUD_SERVICE_ACCOUNT=${APP_ENV^^}_GCLOUD_SERVICE_ACCOUNT
        echo ${!GCLOUD_SERVICE_ACCOUNT} > $HOME/gcloud-service-account.json
        gcloud auth activate-service-account --key-file $HOME/gcloud-service-account.json

        PROJECT=tmt-tools-$APP_ENV
        echo $PROJECT

        IMAGE=eu.gcr.io/$PROJECT/flow-polling
        echo $IMAGE

        APP_RELEASE=$(date +"2.%y%m%d.%H%M%S" | sed -E 's/\.0{1,3}/./g')
        echo $APP_RELEASE

        docker pull $IMAGE:latest || true

        docker build \
          --cache-from $IMAGE:latest \
          --tag $IMAGE:$APP_RELEASE \
          .
        
        docker tag $IMAGE:$APP_RELEASE $IMAGE:latest

        docker push $IMAGE:$APP_RELEASE
        docker push $IMAGE:latest