name: TMT-Charts-CI

on: pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Merge branch delete
      uses: jessfraz/branch-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  