name: Publish

on:
  push:
    branches:
      - master
      - staging
      - junk-ci

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Build Image and Publish
      id: build
      env:
          BRANCH: ${{ github.event.ref }}
          STAGING_GCLOUD_SERVICE_ACCOUNT: ${{ secrets.STAGING_GCLOUD_SERVICE_ACCOUNT }}
          PRODUCTION_GCLOUD_SERVICE_ACCOUNT: ${{ secrets.PRODUCTION_GCLOUD_SERVICE_ACCOUNT }}
      run: |
        BRANCH=${BRANCH#refs/heads/}
        echo $BRANCH
        
        if [ $BRANCH == "master" ]; then
          APP_ENV=production
        elif [ $BRANCH == "staging" ]; then
          APP_ENV=staging
        elif [ $BRANCH == "junk-ci" ]; then
          APP_ENV=staging
        fi
        
        GCLOUD_SERVICE_ACCOUNT=${APP_ENV^^}_GCLOUD_SERVICE_ACCOUNT
        echo ${!GCLOUD_SERVICE_ACCOUNT} > $HOME/gcloud-service-account.json
        gcloud auth activate-service-account --key-file $HOME/gcloud-service-account.json

        PROJECT=tmt-tools-$APP_ENV
        echo $PROJECT

        IMAGE=eu.gcr.io/$PROJECT/flow-polling
        echo $IMAGE

        docker pull $IMAGE:1 || true

        docker build \
          --cache-from $IMAGE:1 \
          --tag $IMAGE \
          .
        
    - name: Generate release version
      uses: themakersteam/tmt-gh-actions/generate-release-version@master
      id: release

    - name: Publish docker image release
      uses: themakersteam/tmt-gh-actions/publish-docker-image-release@master
      with:
        image: eu.gcr.io/tmt-tools-${{ steps.build.APP_ENV }}}/flow-polling
        major-version: ${{ steps.release.outputs.major-version }}
        minor-version: ${{ steps.release.outputs.minor-version }}
        patch-version: ${{ steps.release.outputs.patch-version }}
        latest-tag: true
    